### PR TITLE
feat: add nix flake

### PR DESCRIPTION
**Pull request by theoparis**
`nix run github:theoparis/wl-kbptr`

### CODE REVIEW

**Comment by moverest** [comment]
Thank you for your PR @theoparis. I'm happy to see that someone finds this tool useful even without having "advertised" the project. I'm still trying out stuff and deciding what I want this tool to work and look like. If you have inputs, I'd be happy to hear.

Regarding your changes, I'm trying to keep the build system minimal as maintaining tools across projects can start adding up. However I'd be open to try new things should it make things easier and solve a problem. Could you explain what problem this solves and how you see this being used with the project?

**Comment by theoparis** [comment]
This adds a Nix flake that can be used with the Nix package manager which works on any linux distribution. Nixpkgs provides over 80,000 packages, some of which even work on MacOS.

One thing I did not consider was upstreaming this nix flake to the nixpkgs repository. If I were to create a PR to nixpkgs you could end up using: `nix run nixpkgs#wlr-kbptr`.

**Comment by luftmensch-luftmensch** [comment]
I've now [packaged](https://github.com/NixOS/nixpkgs/pull/312910)

**Comment by moverest** [comment]
Thanks! That's pretty cool. I've added it to the README.

**Pull request closed without merging**
